remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

title: Florian SCHORER
description: L'objectif ici est de vous montrer mes compétences en tant que data scientist - machine learning.

my_linkedin_link: https://www.linkedin.com/in/florianschorer/